config/routes.rb
Rails.application.routes.draw do
  root 'categories#index'
  resources :categories
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :articles do
  
    resources :votes, only: %i[new create destroy]
  end


  resource :session, only: %i[create destroy]
  get 'signin' => 'sessions#new'
  get 'signout' => 'sessions#destroy'
  get 'signup' => 'users#new'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :creator, class_name: 'User'
  belongs_to :category
  has_many :votes, dependent: :destroy
  mount_uploader :image, ImageUploader

  validates :title, :text, :category_id, presence: true
  validates :title, length: { minimum: 5 }
  validates :text, length: { minimum: 10 }


  def self.best_voted_article
    Article.all.max_by { |a| a.votes.count }
  end
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :articles
end

app/models/user.rb
class User < ApplicationRecord
  has_many :votes, dependent: :destroy
  has_many :articles, foreign_key: :creator_id
  validates :username, presence: true, uniqueness: true
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private

  def require_signin
    redirect_to signin_path, alert: 'Please sign in first!' unless current_user
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def show
    @vote = current_user.votes.find_by(article_id: @article.id) if current_user
  end

  def index
    @articles = Article.all
  end

  def new
    if current_user
      @article = Article.new
    else
      redirect_to signin_path
    end
  end

  def create
    @article = Article.new(article_params)
    @article.creator = current_user
    if @article.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      redirect_to article_path(@article)
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
    redirect_to root_path
  end
  private

  def article_params
    params.require(:article).permit(:title, :text, :image, :prix_max, :prix_min, :category_id)
  end

  def set_article
    @article = Article.find(params[:id])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all.includes(:articles)
    @best_voted_article = Article.best_voted_article
  end

  def show
    @category = Category.includes(:articles).find_by(id: params[:id])
    @category_articles = @category.articles.reverse
  end

  def new
    @category = Category.new
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:email])
    if user
      session[:user_id] = user.id
      redirect_to root_path, notice: "Welcome back, #{user.username}!"
    else
      flash.now[:alert] = 'Unregistered User!'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to categories_url, notice: "You're now signed out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.includes(:articles).find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'Thanks for signing up!'
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username,:email,:password)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :require_signin

  def create
    @article = Article.find(params[:article_id])
    @article.votes.create!(user: current_user)

    redirect_to @article
  end

  def destroy
    vote = current_user.votes.find(params[:id])
    vote.destroy

    article = Article.find(params[:article_id])
    redirect_to article
  end

  private

  def vote_params
    params.require(:vote).permit(:article_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def random_image(category)
    # rubocop:disable Layout/LineLength
    links = ['https://images.unsplash.com/photo-1517180102446-f3ece451e9d8?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80', 'https://images.unsplash.com/photo-1551122102-63cd339bfaab?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1051&q=80', 'https://images.unsplash.com/photo-1579468118864-1b9ea3c0db4a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80', 'https://s3.amazonaws.com/ckl-website-static/wp-content/uploads/2017/07/Banner_css-1280x680.png']
    # rubocop:enable Layout/LineLength
    links[category - 1]
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def vote_button(article, vote)
    if vote
      button_to 'Unlike', article_vote_path(article, vote), method: :delete
    else
      button_to 'like', article_votes_path(article)
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |f| %>
  <%= render "shared/errors", object: article %>

  <%= f.label :title %>
  <%= f.text_field :title, autofocus: true ,class: 'form-control', required: true %>

  <%= f.label :text %>
  <%= f.text_area :text, rows: 10 ,class: 'form-control', required: true %>

  <%= f.collection_select :category_id, Category.all, :id, :name,{prompt: "Select A Category"},class: 'form-control' %>
  
  <%# <fieldset> %>
    <%= f.label :image %>
    <%= f.hidden_field :image_cache %>
    <%= f.file_field :image, accept: 'image/jpeg,image/gif,image/png' %>
  <%# </fieldset> %>

      
      <%= f.label :prix_max, 'Prix :' %>
      <%= f.number_field :prix_max, class: 'form-control', required: true, min: 0 %>

        <%= f.label :Ville %>
         <%= f.text_field :ville,class: 'form-control', required: true%>

  <%= f.submit :CRRER_ANNONCE%>
<% end %>

app/views/articles/destroy.html.erb
<h1>Are you sure you want to delete this article?</h1>
<p><strong>Title:</strong> <%= @article.title %></p>
<p><strong>Text:</strong> <%= @article.text %></p>
<%= link_to "Delete", article_path(@article), method: :delete, class: "btn btn-danger" %>
<%= link_to "Cancel", article_path(@article), class: "btn btn-secondary" %>

app/views/articles/edit.html.erb
<div class="article-form">
  <%= form_for @article do |f| %>
    <% if @article.errors.any? %>
      <div class="alert alert-danger">
        <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :text %>
      <%= f.text_area :text, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :image %>
      <%= f.file_field :image, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :prix %>
      <%= f.number_field :prix_max, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :category_id %>
      <%= f.select :category_id, Category.all.collect { |c| [c.name, c.id] }, {}, { class: "form-control" } %>
    </div>
    <%= f.submit "Update", class: "btn btn-primary" %>
  <% end %>
</div>

<style>
    .article-form {
  max-width: 600px;
  margin: 0 auto;
  padding: 20px;
  border: 1px solid #ccc;
  border-radius: 5px;
}

.article-form .form-group {
  margin-bottom: 20px;
}

.article-form label {
  font-weight: bold;
  display: block;
  margin-bottom: 5px;
}

.article-form input[type="text"],
.article-form textarea,
.article-form select {
  width: 100%;
  padding: 10px;
  border: 1px solid #ccc;
  border-radius: 5px;
  box-sizing: border-box;
}

.article-form input[type="submit"],
.article-form a.btn {
  display: inline-block;
  padding: 10px 20px;
  background-color: #007bff;
  color: #fff;
  border: none;
  border-radius: 5px;
  cursor: pointer;
  transition: background-color 0.3s;
}

.article-form input[type="submit"]:hover,
.article-form a.btn:hover {
  background-color: #0062cc;
}

.alert-danger {
  color: #721c24;
  background-color: #f8d7da;
  border-color: #f5c6cb;
  margin-bottom: 20px;
  padding: .75rem 1.25rem;
  border: 1px solid transparent;
  border-radius: .25rem;
}
    </style>

app/views/articles/index.html.erb
<div class="articles">
  <% @articles.each do |article| %>
    <div class="article">
      <h2 class="article-title"><%= link_to article.title, article_path(article) %></h2>
      <% if article.image.present? %>
        <%= image_tag article.image.url %>
      <% end %>
      <p class="article-text"><%= truncate(article.text, length: 200) %></p>
      <% if current_user && current_user == article.creator %>
        <%= link_to "Edit", edit_article_path(article) %>
        <%= link_to "Delete", article_path(article), method: :delete, data: { confirm: "Are you sure you want to delete this article?" } %>
      <% end %>
    </div>
  <% end %>
</div>







<h1><%= @title %></h1>

<% @articles.each do |article| %>
  <section class="article">
    <div class="summary">
      <h2>
        <%= link_to article.title, article_path(article) %>
      </h2>
      <%= image_tag article.image.url%>
      <p>
        <%= truncate(article.text, length: 150, separator: ' ') %>
      </p>
      <span class= "ml-3 "><%= pluralize(article.votes.count, 'like') %></span>
      
      <p>
        Created by 
        <strong><%= article.creator.username %></strong>,
        <%= time_ago_in_words(article.created_at) %> ago<%= %> 
      </p>

    </div>
  </section>
<% end %>

app/views/articles/new.html.erb
<div class="article-new-container">
<h1>DEPOSER VOTRE  ANNONCE</h1>
<%= render "form", article: @article %>
</div>

app/views/articles/show.html.erb
<div class= 'article-show-container'>
  <%= image_tag( @article.image.url ? @article.image.url : random_image(@article.category_id)) %>
  <h1 class=""><%= @article.title%></h1>
  <p class="articles-text"><%= @article.text%></p>
  <span class= ''>Author : <strong class="" ><%= @article.creator.username %> </strong></span>
       <p class="article-price">Prix : <%= number_to_currency(@article.prix_max)%></p>

  <span ><%= pluralize(@article.votes.count, 'like') %></span>
    <%= vote_button(@article,@vote) %>
    <% if current_user && current_user == @article.creator %>
    <%= link_to "Edit", edit_article_path(@article) %>
    <%end%>
</div>




<style>


.article-show-container p.articles-text {
  margin: 0;
  margin-bottom: 10px;
  max-width: 800px; /* ou toute autre valeur que vous souhaitez */
  word-wrap: break-word;
}



.article {
  margin-bottom: 20px;
  border: 1px solid #ccc;
  border-radius: 5px;
  padding: 20px;
}

.article-title {
  font-size: 24px;
  font-weight: bold;
  margin-top: 0;
  margin-bottom: 10px;
}

.article-text {
  text-align: justify;
  margin: 0;
  margin-bottom: 20px;
  line-height: 1.5;
}

.articles {
  display: flex;
  flex-wrap: wrap;
  justify-content: space-between;
}

.articles .article {
  width: 48%;
}

.articles .article img {
  width: 100%;
  height: auto;
  margin-bottom: 10px;
}

.articles .article a {
  display: block;
  margin-top: 10px;
}
</style>

app/views/categories/index.html.erb
<% if @best_voted_article %>
<h1 class="home-title">Most liked products</h1>
  <div class="home-best-article-container">
    <%= link_to article_path(@best_voted_article.id) do%>
      <%= image_tag(@best_voted_article.image.url ? @best_voted_article.image.url : random_image(@best_voted_article.category_id)) %>
      <h2 class="article-title">
        <%= @best_voted_article.title %>
      </h2>
      <p class="article-text"><%= truncate(@best_voted_article.text , length: 400)%></p>
    <%end%>
  </div>
<% end %>

<h2 class="home-subtitle">Categories</h2>
<div class="home-articles-container">
  <% Category.all.each do |category|%>
    <% most_recent_article = category.articles.last %>
    <% if most_recent_article %>
      <div class="home-article-container">
      <%= link_to category_path(category.id) do %>
          <%= image_tag( most_recent_article.image.url ? most_recent_article.image.url : random_image(category.id)) %>
          <h2 ><%= category.name %></h2>
          <h5><%= truncate(most_recent_article.title,length:20)%></h5>
      <% end %>
      </div>
    <%end%>
  <% end %>
</div>

<style>
  .home-title {
  font-size: 36px;
  font-weight: bold;
  text-align: center;
  margin-top: 50px;
}

.home-best-article-container {
  display: flex;
  flex-direction: column;
  align-items: center;
  margin-top: 50px;
}

.home-best-article-container h2.article-title {
  font-size: 24px;
  font-weight: bold;
  margin-top: 20px;
  margin-bottom: 10px;
  text-align: center;
}

.home-best-article-container p.article-text {
  text-align: justify;
  margin: 0;
  margin-bottom: 20px;
  line-height: 1.5;
  max-height: 200px;
  overflow: hidden;
  text-overflow: ellipsis;
}

.home-best-article-container img {
  border: 1px solid white;
  border-radius: 5px;
  object-fit: cover;
  box-shadow: 10px 5px 5px grey;
  width: 100%;
  max-width: 600px;
  max-height: 400px;
  height: auto;
  transition: 0.3s;
}

.home-best-article-container img:hover {
  transform: scale(1.1);
  cursor: pointer;
}
  
  </style>

app/views/categories/show.html.erb
<div class="category-show-container">
  <% @category_articles.each do |article| %>
    <%= link_to article_path(article) do %>
      <%= image_tag(article.image.url || random_image(@category.id))  %>
      <div class="article-info">
        <h2 class="article-title"><%= truncate(article.title, length: 25) %></h2>
        <p class="article-text"><%= truncate(article.text, length: 100) %></p>
        <p class="article-price">Prix : <%= number_to_currency(article.prix_max)%></p>
        <%= pluralize(article.votes.count, 'like') %>
      </div>
    <% end %>
  <% end %>
</div>
<style>
  
 .category-show-container {
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
}

.category-show-container a {
  display: grid;
  grid-template-columns: 200px 1fr;
  grid-gap: 20px;
  align-items: center;
  width: 100%;
  max-width: 600px;
  margin: 20px;
  padding: 20px;
  box-shadow: var(--box-shadow);
  transition: 0.3s;
  border-radius: 5px;
  color: var(--on-background);
  background-color: var(--background);
}

.category-show-container img {
  border: 1px solid white;
  border-radius: 5px;
  object-fit: cover;
  box-shadow: 10px 5px 5px grey;
  width: 100%;
  height: 100%;
}

.category-show-container .article-info {
  display: flex;
  flex-direction: column;
  justify-content: center;
}

.category-show-container h2.article-title {
  font-size: 20px;
  font-weight: bold;
  margin: 0;
  margin-bottom: 10px;
}

.category-show-container p.article-text {
  margin: 0;
  margin-bottom: 10px;
  max-width: 340px; /* ou toute autre valeur que vous souhaitez */
  word-wrap: break-word;
}

.category-show-container p.article-price {
  margin: 0;
}

.category-show-container a:hover {
  text-decoration: none;
  background-color: rgb(226, 226, 226);
  border-bottom: none;
  color:black;
  transform: translateY(-5px);
}
  </style>

app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>
  <%= content_tag(:div, message, class: "flash #{type}") %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Articles</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/css/all.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://fonts.googleapis.com/css2?family=Pangolin&display=swap' %>

  </head>

  <body>
    <%= render "layouts/header" %>
    <%= render "layouts/flash" %>

    <div class="content">
      <%= yield %>
    </div>

    <%= render "layouts/footer" %>
    <%# <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
   
  </body>
</html>
<script>
  // Dark-Light-Mode Toggle
var toggleSwitch = document.querySelector('input[type="checkbox"]');
var nav = document.getElementById("nav");
var toggleIcon = document.getElementById("toggle-icon");

// Dark Mode Styles
function darkMode() {
  nav.style.backgroundColor = "rgb(0 0 0 / 50%)";
  toggleIcon.children[0].textContent = "Dark Mode";
  toggleIcon.children[1].classList.replace("fa-sun", "fa-moon");
  // imageMode("dark");
}

// Light Mode Styles
function lightMode() {
  nav.style.backgroundColor = "rgb(255 255 255 / 50%)";
  toggleIcon.children[0].textContent = "Light Mode";
  toggleIcon.children[1].classList.replace("fa-moon", "fa-sun");
}

// Switch Theme Dynamically
function switchTheme(event) {
  if (event.target.checked) {
    document.documentElement.setAttribute("data-theme", "dark");
    localStorage.setItem("theme", "dark");
    darkMode();
  } else {
    document.documentElement.setAttribute("data-theme", "light");
    localStorage.setItem("theme", "light");
    lightMode();
  }
}

// Event Listener
toggleSwitch.addEventListener("change", switchTheme);

// Check Local Storage for Theme
var currentTheme = localStorage.getItem("theme");

if (currentTheme) {
  document.documentElement.setAttribute("data-theme", currentTheme);

  if (currentTheme === "dark") {
    toggleSwitch.checked = true;
    darkMode();
  }
}

  </script>